version: 2

jobs:
  build:
    docker:
<<<<<<< HEAD
      - image: quay.io/rust-lang-ja/circleci:mdbook-0.4.5-rust-1.49.0
    parallelism: 1
    steps:
      - checkout
      # Remove .gitconfig added by Circle CI as cargo doesn't support ssh authorization
      - run: rm -f ~/.gitconfig
      - run: rm -rf rust-toolchain docs
      - run: rustc -V
      - run: mdbook -V
      - run: mdbook test
      - run: mdbook build
      - run: cargo run --bin lfp src
      # TODO: Run link2print here. (See ci/build.sh on the master branch)
      # - run: TODO
      - store_artifacts:
          path: docs
      # Restore a deleted file.
      - run: git checkout rust-toolchain
      - deploy:
          name: If master-ja branch, publish to GitHub Page
          command: |
            if [ "x_${CIRCLE_BRANCH}" == "x_master-ja" ]; then
              git config user.name "bn-e (CircleCI)"
              git config user.email "bn-e@hibaridb.org"
              ./tools/circleci/push-to-master-ja.sh
            fi
=======
      - image: cimg/base:stable
    parallelism: 1
    branches:
      ignore:
        - master
        - second-edition-ja
    steps:
      - run:
          name: Print error and exit
          command: |
            echo "ERROR: Wrong '.circleci/config' for $CIRCLE_BRANCH branch."
            echo "       Please contact the developer (e.g. tatsuya6502) to fix."
            exit 8
>>>>>>> upstream/master
